# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf69b38ecc9c3bac6127f47dabddbde389e84c6cb61d71ff83b01f70deead0c60a7e3075ab37ad4c798e348293b84d6787949ad65188d93ada867f2f46a77e82

test:
  secret_key_base: f730a67e6855d13c24fb9699eef9f6525f74cdcbac7647a3bb41af6ded2131a62cbea1b70b0e423eb6dbf399bd5d7301853b5198e634a0bd2728ce6bc125b610

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
