# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76b7e274c23bf506bbb429f11e720c3d6c0809735efe9e798619d2b2a54ebbff1215244e6b4ab577b1c5c6d8949991546bbbe639993db4b98509dccd6a6fe9e5

test:
  secret_key_base: a3a0811db1f0252a17f135a6acd3da1feb0056e6c6dadc743aedf689e18230c162c216c8d05dd9d52b31562cb63dcb7811b2eab924c3850db8e7206d333ae168

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
